site/source/apps/techblog/urls.py
from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse
from techblog import views
from techblog.feeds import ArticlesFeed

urlpatterns = patterns('techblog.views',
    (r'^(?:articles/)?$', views.ArticleList.as_view()),
    (r'^articles/add/$', 'add_or_edit_article'),
    url(r'^articles/(?P<article_id>\d+)/$', views.ArticleDetail.as_view(), name='view_article'),
    url(r'^articles/(?P<article_id>\d+)/edit/$', 'add_or_edit_article', name='edit_article'),
    url(r'^articles/(?P<article_id>\d+)/translate/$', 'translate_article', name='translate_article'),
    (r'^articles/(\d+)/(publish|unpublish)/$', views.ArticlePublisher.as_view()),

    (r'^markitup/preview/(\w+)/$', views.MarkitupPreviewer.as_view()),

    (r'^users/$', views.UserProfilesList.as_view()),
    url(r'^users/(?P<user_name>\w+)/$', views.UserProfileDetail.as_view(), name='user_profile'),
    (r'^profile/$', views.UserProfileDetail.as_view()),
    (r'^profile/edit/$', views.UserProfileEdit.as_view()),
    (r'^users/(?P<user_name>\w+)/marked/$', 'marked_by_user'),

    (r'^tags/$', views.TagsList.as_view()),

    (r'^api/parse_html/$', 'parse_html'),

    url(r'^rss/$', ArticlesFeed(), name='rss'),

)

site/source/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

MEDIA_ROOT = getattr(settings, 'MEDIA_ROOT', '/media/')
MEDIA_URL = getattr(settings, 'MEDIA_URL', '/media/')
STATIC_ROOT = getattr(settings, 'STATIC_ROOT', '/static/')
STATIC_URL = getattr(settings, 'STATIC_URL', '/static/')

urlpatterns = patterns('',
    ## External applications mappings
    (r'^admin_tools/', include('admin_tools.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.urls')),
	(r'^robots\.txt$', 'django.views.generic.simple.redirect_to', {'url': '%srobots.txt' % STATIC_URL[1:]}),
    (r'^comments/', include('django.contrib.comments.urls')),
	## Internal applications mappings
    (r'', include('techblog.urls')),
)
     
# Adding debug-mappings
if settings.DEBUG:
    # Debug media and static
    urlpatterns += patterns('',
                            (r'^%s(?P<path>.*)$' % MEDIA_URL[1:], 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
                            (r'^%s(?P<path>.*)$' % STATIC_URL[1:], 'django.views.static.serve', {'document_root': STATIC_ROOT}),
                            )

site/source/apps/techblog/models.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-
from datetime import datetime
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models.aggregates import Count
from django.db.models.fields.files import ImageField
from django.db.models.signals import post_save
from django.db.models import Q
from taggit.managers import TaggableManager
from techblog.functions import html_parser, binary_date, formatted_date
from techblog.constants import GENDER_MALE, GENDER_FEMALE
from django.conf import settings


class Language(models.Model):
    class Meta:
        verbose_name = u'Language'
        verbose_name_plural = u'Languages'
        ordering = ('title',)

    title = models.CharField(max_length=25, verbose_name=u'Title')
    slug = models.SlugField(max_length=64, default="", unique=True, db_index=True, verbose_name=u'Slug')

    def __unicode__(self):
        return self.title


class Category(models.Model):
    class Meta:
        verbose_name = u'Category'
        verbose_name_plural = u'Categories'
        ordering = ('title',)

    title = models.CharField(max_length=64, verbose_name=u'Title')
    slug = models.SlugField(max_length=64, verbose_name=u'Text link to the article in browser', help_text=u"only English letters, sample 'time_management_for_the_masses'", default="")

    def __unicode__(self):
        return self.title

    @staticmethod
    def get_categories_with_count():
        categories = Category.objects.all()
        categories = categories.annotate(count=Count('article__id')).filter(count__gt=0).order_by('-count')
        return categories


class Article(models.Model):
    class Meta:
        verbose_name = u'Article'
        verbose_name_plural = u'Articles'
        ordering = ('-date',)

    author = models.ForeignKey(User, verbose_name=u'Author', null=True, blank=True)
    authors = models.ManyToManyField(User, verbose_name=u'Authors', null=True, related_name='authors')
    title = models.CharField(u'Title', max_length=1024)
    date = models.DateTimeField(u'Publication date', default=datetime.now())
    is_public = models.BooleanField(u'Is published?', default=False)
    notified_on_first_publish = models.BooleanField(default=False, editable=False)

    lang = models.ForeignKey(Language, verbose_name=u'Language')
    parent = models.ForeignKey('self',  related_name='parent_article', blank=True, null=True, verbose_name=u'Parent', help_text='The article, which directly is translated.')
    original = models.ForeignKey('self', related_name='original_article', blank=True, null=True, verbose_name=u'Original', help_text='The original article.')

    MARKUP_HTML = u'html'
    MARKUP_MARKDOWN = u'markdown'
    MARKUP_RST = u'rst'
    MARKUP_TEXTILE = u'textile'
    MARKUP_TYPE = (
        (MARKUP_HTML, u'HTML'),
        (MARKUP_MARKDOWN, u'Markdown'),
        (MARKUP_RST, u'ReStructuredText'),
        (MARKUP_TEXTILE, u'Textile'),
    )
    markup = models.CharField(u'Format', max_length=16, default=MARKUP_HTML, choices=MARKUP_TYPE)
    short_raw = models.TextField(u'Short')
    description_raw = models.TextField(u'Undercut', blank=True)

    short = models.TextField(u'Short (result)')
    description = models.TextField(u'Undercut (result)', blank=True)
    tags = TaggableManager(blank=True)
    category = models.ForeignKey(Category, null=True, blank=True)

    untranslated_langs = None

    def __unicode__(self):
        return self.title

    @classmethod
    def get_published(cls):
        return cls.objects.filter(is_public=True)

    def get_translations(self):
        query = self.get_published()
        if self.is_original():
            query = query.filter(original=self)
        else:
            query = query.filter(Q(original=self.original) | Q(id=self.original.id), ~Q(id=self.id))
        query = query.select_related('author', 'lang')
        return query

    def save(self, *args, **kwargs):

        from techblog.services.articles import ArticleService
        rendered_article = ArticleService.render_markups(self)

        self.short = rendered_article.short
        self.description = rendered_article.description

        super(Article, self).save(*args, **kwargs) # Call the "real" save() method.

    def is_original(self):
        return self.original is None

    def binary_date(self):
        return binary_date(self.date)

    def formatted_date(self):
        return formatted_date(self.date)

    def get_absolute_url(self):
        return reverse('view_article', args=(self.id,))


class UserProfile(models.Model):
    """
     After profile is created you may access it from User instance: userobj.get_profile()
    """
    class Meta:
        verbose_name = u'User profile'
        verbose_name_plural = u'User profiles'

    def __unicode__(self):
        return u"Profile of user: '%s'" % self.user.username

    user = models.ForeignKey(User, unique=True)
    GENDERS = (
        (GENDER_MALE, u'Male'),
        (GENDER_FEMALE, u'Female'),
    )
    gender = models.CharField(u'Gender', max_length=16, choices=GENDERS, blank=True, null=True)
    birth_date = models.DateField(u'Birthday', blank=True, null=True)
    avatar = ImageField(u'Foto', blank=True, null=True, upload_to='users/')
    use_gravatar = models.BooleanField(u'Use Gravatar', default=False)
    about_me = models.TextField(u'About me', max_length=4096, blank=True, null=True)
    
    def get_articles_count(self):
        count = Article.objects.filter( authors__in=[self.user], is_public=True).count()
        return count

    def gravatar(self): pass

def handle_user_creation_signal(sender, instance, **kwargs):
    """
     Unfortunately, User's profile doesn't created automatically. Thus we need to handle User creation signal.
    """
    try:
        profile = instance.get_profile()
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=instance)
        profile.save()
post_save.connect(handle_user_creation_signal, sender=User)

site/source/apps/techblog/views/api.py
from django.http import HttpResponse, HttpResponseForbidden
from techblog.functions import html_parser

def parse_html(request):
    if request.user.is_authenticated():
        return HttpResponse(html_parser(request.POST.get('data', '')))
    else:
        return HttpResponseForbidden()

site/source/apps/techblog/views/articles.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger, InvalidPage
from django.views.generic.base import TemplateView
from django.views.generic.list_detail import object_list, object_detail
from django.views.generic import ListView, DetailView, RedirectView, CreateView
from django.views.generic.simple import direct_to_template
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.shortcuts import redirect, get_object_or_404
from datetime import datetime

from techblog.forms import ArticleForm, TranslateArticleForm
from techblog.models import Article, UserProfile, Category, Language
from techblog.services.articles import ArticleService
from techblog.logic.mail_service import MailService
from techblog.constants import ARTICLES_LIMIT


class ArticlesControlPanel(object):
    article_service = ArticleService()

    def init_articles(self):
        self.articles = self.article_service.filter_articles(self.request).order_by('-date')

    def get_control_panel_context(self):
        return self.article_service.get_control_panel_context(self.articles)


class ArticleList(TemplateView, ArticlesControlPanel):
    template_name = 'articles/article_list.html'

    def get_context_data(self, **kwargs):
        context = super(ArticleList, self).get_context_data(**kwargs)
        context['page'] = 'articles_page'

        self.init_articles()
        context.update(self.get_control_panel_context())

        if context.has_key('own_articles'):
            context['own'] = 'articles'
        elif context.has_key('own_drafts'):
            context['own'] = 'drafts'

        paginator = Paginator(list(self.articles), ARTICLES_LIMIT)

        try:
            page_num = int(self.request.GET.get('page', '1'))
        except ValueError:
            page_num = 1
        try:
            current_page = paginator.page(page_num)
        except (EmptyPage, InvalidPage):
            current_page = paginator.page(paginator.num_pages)

        article_list = list(current_page.object_list)
        for article in article_list:
            article.untranslated_langs = ArticleService.get_untranslated_ids(article)
        context["article_list"] = article_list

        if current_page.has_next():
            preview_page = paginator.page(page_num + 1)
            context['next_page'] = page_num + 1
            context['preview_articles'] = list(preview_page.object_list)

        return context


class TranslateArticle(CreateView):
    template_name = 'articles/translate_article.html'
    form_class = TranslateArticleForm

    def form_valid(self, form, *args, **kwargs):
        form.instance.author = self.request.user

        if 'is_public' in self.request.POST:
            form.instance.is_public = True
        else:
            form.instance.is_public = False

        form.save()
        form.instance.authors.add(self.request.user)

        if form.instance.is_public:
            MailService().send_mail_on_first_article_publish(form.instance, self.request.user)

        return redirect( reverse('view_article', args=(form.instance.id,)) )

    def get_initial(self):
        initial = super(TranslateArticle, self).get_initial().copy()
        article_id = self.kwargs.get('article_id')

        article = get_object_or_404(Article, id=article_id)
        data = ArticleService.get_translation_data(article, self.request.user)

        initial.update(data)
        return initial

translate_article = TranslateArticle.as_view()


def add_or_edit_article(request, article_id=None, action=None):
    mail_service = MailService()

    params = {}

    if request.user.is_authenticated():
        params['page'] = 'add_article'
        params['edit_allowed'] = True

        article = None
        if article_id:
            try:
                article = Article.objects.get(id=article_id)
                if article.author == request.user:
                    params['page'] = 'edit_article'
                else:
                    params['edit_allowed'] = False
            except Article.DoesNotExist:
                pass

        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                # Process the data in form.cleaned_data
                article = form.save(commit=False)
                if 'is_public' in request.POST:
                    article.is_public = True
                    if not article.date:
                        article.date = datetime.now()
                else:
                    article.is_public = False
                article.author = request.user # Todo: remove this
                article.save()
                article.authors.add(request.user)
                
                tags = form.cleaned_data['tags']
                article.tags.clear()
                for tag in tags:
                   article.tags.add(tag)

                if article.is_public:
                    mail_service.send_mail_on_first_article_publish(article, request.user)
                return redirect('/articles/%s/' % article.id)
        else:
            form = ArticleForm(instance=article) # An unbound form
        params['form'] = form
    return direct_to_template(request, 'articles/add_or_edit_article.html', params)


class ArticleDetail(DetailView, ArticlesControlPanel):
    template_name = 'articles/view_article.html'

    def get_object(self, queryset=None):
        article = get_object_or_404(Article, id=(self.kwargs.get('article_id')))

        self.is_public = article.is_public
        if article.is_public or self.request.user in article.authors.all():
            return article
        else:
            return None

    def get_context_data(self, **kwargs):
        context = super(ArticleDetail, self).get_context_data(**kwargs)
        self.init_articles()
        context.update(self.get_control_panel_context())
        context['page'] = 'articles_page'
        context['sub_page'] = 'view_article'
        context['is_public'] = self.is_public
        if self.object:
            context['edit_allowed'] = self.object.author == self.request.user

        return context


class ArticlePublisher(RedirectView):
    permanent = False
    article_service = ArticleService()

    def get_redirect_url(self, **kwargs):
        article_id, action =  self.args
        article = get_object_or_404(Article, id=article_id)
        url = '/articles/%s/' % article_id
        if article.author == self.request.user:
            if action == 'publish':
                self.article_service.publish_article(article, self.request.user)
            elif action == 'unpublish':
                self.article_service.unpublish_article(article, self.request.user)
        return url

site/source/apps/techblog/views/markitup.py
from django.views.generic import View, TemplateView
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from techblog.services.articles import ArticleService

class MarkitupPreviewer(TemplateView):
    template_name = "markitup/article_preview.html"

    def get_context_data(self, **kwargs):
        context = super(MarkitupPreviewer, self).get_context_data(**kwargs)

        markup = self.args[0]
        data = self.request.POST.get("data")

        context["rendered_data"] = ArticleService.render_markup(markup, data)
        return context

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return login_required( super(MarkitupPreviewer, self).dispatch )(request, *args, **kwargs)

site/source/apps/techblog/views/tags.py
from django.http import HttpResponse

from django.views.generic import TemplateView
from techblog.services.tags import TagService

class TagsList(TemplateView):
    template_name = 'tags/tags_list.html'

    def get_context_data(self, **kwargs):
        context = super(TagsList, self).get_context_data(**kwargs)
        context['categories'] = TagService.get_category_tag_cloud()
        context['page'] = 'tags_page'
        return context

#def tag_cloud(request, params={}, *args, **kwargs):
#    params['page'] = 'tag_cloud'
#    return HttpResponse('tag cloud')
#    #return object_list(request, models.Article.objects.filter(is_staff=False, is_superuser=False), template_name='pages/user_list.html', extra_context=params)

site/source/apps/techblog/templates/articles/add_or_edit_article.html
{% extends 'abstract/base.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/techblog/css/big_forms.css"/>
    <link rel="stylesheet" href="/static/techblog/css/pages/add_or_edit_article.css"/>
    <link rel="stylesheet" href="/static/pygments/css/highlight_native.css"/>
{% endblock css %}

{% block media %}
    {{ form.media }}
{% endblock media %}

{% block content %}
    {% if user.is_authenticated %}
        {% if edit_allowed %}
            <h1 class="big-form-title">Article</h1>

            {% include 'articles/article_edit_form.html' %}

        {% else %}
            <h1 class="big-form-title">Cheating?</h1>
            <div class="big-form-text">
                You are trying to edit someone else's article! We have it banned!
            </div>
        {% endif %}
    {% else %}
        <h1 class="big-form-title">Authorize</h1>
        <div class="big-form-text">
            You are not logged in and can't work with the articles. <a href="{% url auth_login %}">Login</a> and get those rights.
        </div>
    {% endif %}
{% endblock content %}

site/source/apps/techblog/templates/articles/article_edit_form.html
<form method="post" class="large-form">
    {% csrf_token %}
    <dl>
        {% for field in form %}
            {% if field.is_hidden %}
                <dd>{{ field }}</dd>
            {% else %}

                <dt>{{ field.label_tag }}</dt>
                <dd>
                    {{ field }}
                    {% if field.help_text %}
                        <div class="hint">{{ field.help_text }}</div>
                    {% endif %}
                    {% if field.errors %}
                        <div class="myerrors">{{ field.errors }}</div>
                    {% endif %}
                </dd>
            {% endif %}
        {% endfor %}
    </dl>
    <div class="form-actions">
        <input type="submit" class="submit-form" name="is_public" value="Publish"/>
        <input type="submit" class="submit-form" name="is_draft" value="To draft"/>
    </div>
</form>

<script type="text/javascript">
    // < ![CDATA[
    (function () {
        var u = document.getElementById('id_title');
        if (u) u.focus();
    })();
    // ]]>
</script>

site/source/apps/techblog/templates/articles/article_item.html
{% load user_avatar %}

<div class="article-item">
    <div class="item-date-block">
        <div class="binary-date">
            {{ article.binary_date|safe }}
        </div>
        <div class="formatted-date">
            {{ article.formatted_date|safe }}
        </div>
    </div>

    {% if request.user.is_authenticated %}
    <div class="commands">
        {% if request.user in article.authors.all %}
            <div class="item-command">
                <a href="{{ article.get_absolute_url }}edit/" title="Edit article">Edit</a>
            </div>
            <div class="item-command">
                {% if article.is_public %}
                    <a href="{{ article.get_absolute_url }}unpublish/" title="Move article to draft">To draft</a>
                {% else %}
                    <a href="{{ article.get_absolute_url }}publish/" title="Publish article">Publish</a>
                {% endif %}
            </div>
        {% endif %}

        {% if article.untranslated_langs %}
            <div class="item-command">
                <a href="{{ article.get_absolute_url }}translate/" title="Translate">Translate</a>
            </div>
        {% endif %}
    </div>
    {% endif %}

    <div class="article-item-block">
        <div class="min-height"></div>
        <div class="article-content">

            <h2 class="article-lang"> {{ article.lang.slug }} </h2>

            {% if sub_page == 'view_article' %}
                <h2 class="article-title">
                    {% if article.category %}
                        <span class="category" >
                            <a href="/articles/">Articles</a> &rarr;
                        </span>
                    {% endif %}
                    {{ article.title }}
                </h2>
            {% else %}
                <h2 class="article-title">
                    <a href="/articles/{{ article.id }}/">{{ article.title }}</a>
                </h2>
            {% endif %}

            {% if not article.is_original %}
                <div class="translation-link">
                    <img src="/static/techblog/img/pages/articles/arrow.png" width="20" height="6">
                    Translation for <a href="{% url view_article article_id=article.original.id  %}">{{ article.original.title }}</a>
                    ({{ article.original.lang.slug }})
                </div>
            {% endif %}

            <div class="article-info">
                {% if article.category %}
                    <div class="article-category">
                       <a href="?category={{ article.category.slug }}" title="Category: {{ article.category.title }}">{{ article.category.title }}</a> :
                    </div>
                {% endif %}
                {% with article.tags.all as article_tags %}
                    {% if article_tags %}
                        <div class="article-tags">
                            {% for tag in article_tags %}
                                <a href="/?tags={{ tag }}">{{ tag }}</a> {% if forloop.last %}{% else %}, {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endwith %}
                <div class="article-likes">
                    {% include "articles/social_connections.html" %}
                </div>
            </div>
            <div class="clear"></div> <!-- IE6 fix -->

            <div class="article-short rich-content">
                {{ article.short|safe }}
            </div>
            {% if sub_page != 'view_article' %}
                <div class="article-bottom-block">
                    <div class="article-undercut">
                        <a href="/articles/{{ article.id }}/#undercut">Read more</a>
                    </div>
                    <div class="item-authors">
                        <div class="authors-title">
                            Authors:
                        </div>
                        {% for author in article.authors.all %}
                            <div class="item-author-block">
                                <div class="item-author-photo">
                                    <a href="/users/{{ author.username }}/">{% user_avatar author 50 %}</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            {% if sub_page == 'view_article' %}
                <a name="undercut"></a>
                <div class="article-uncut rich-content">
                    {{ article.description|safe }}
                </div>
            {% endif %}
            {% if article_mode == 'description' %}
                <div class="article-info">
                    {% with article.tags.all as article_tags %}
                        {% if article_tags %}
                            <div class="article-tags">
                                {% for tag in article_tags %}
                                    <a href="/?tags={{ tag }}">{{ tag }}</a> {% if forloop.last %}{% else %}, {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    {% endwith %}
                    <div class="article-likes">
                        {% include "articles/social_connections.html" %}
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="clear"></div> <!-- IE6 fix -->
    </div>

    {% with article.get_translations as translations %}
        {% if translations %}
            <div class="article-translations">
                {% for translation in translations %}
                    <div class="translation-item {% if forloop.last %}last-item{% endif %}">

                        <div class="left-block">
                            <span class="translation-lang">{{ translation.lang.slug }}</span>
                            <span class="translation-title">
                                <a href="{% url view_article article_id=translation.id %}">
                                    {{ translation.title }}
                                </a>
                            </span>
                        </div>

                        <div class="right-block">
                            <span class="translation-date">{{ translation.date|date:"d M Y H:i" }}</span>
                            {% if translation.is_original %}
                                <span class="type-original">Original</span>
                            {% else %}
                                <span class="type-translation">Translation</span>
                            {% endif %}
                            <span class="translation-authors">
                                {% for author in translation.authors.all %}
                                     <a href="{% url user_profile user_name=author.username %}">{{ author.username }}</a>
                                     {% if not forloop.last %}, {% endif %}
                                {% endfor %}
                             </span>
                        </div>

                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

</div>

{% if sub_page == 'view_article' %}
    <h1 class="comments-title">Comments</h1>

    {% include 'articles/comment_tree.html' %}

    <a name="last_comnent"></a>

    <div id="bottom-comment-form">
        {% if user.is_authenticated %}
            {% include 'articles/comment_form.html' %}
        {% else %}
            You are not logged in and can't write comments. <a href="{% url auth_login %}">Login</a> and get those rights.
        {% endif %}
    </div>
{% endif %}

site/source/apps/techblog/templates/articles/article_list.html
{% extends 'abstract/base.html' %}

{% load update_filters %}

{% block title %}Progressive web-dev lives here / Articles / PROGRESSORS{% endblock %}

{% block meta_keywords %}
    <meta name="title" content="Progressive web-dev lives here / Articles / PROGRESSORS"/>
    {% include "include/common_meta_tags.html" %}
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/techblog/css/pages/articles.css"/>
    <link rel="stylesheet" href="/static/pygments/css/default.css"/>
{% endblock css %}

{% block script %}
    <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    <script type="text/javascript" src="http://platform.linkedin.com/in.js"></script>
{% endblock %}


{% block content %}

    <div class="articles-block">
        <div class="articles-languages">
             <div class="language-link all-languages-link">
                <a href="/articles/{% update_filters the_filter all_langs=1 %}">All</a>
            </div>
            {% for lang in languages %}
                <div class="language-link {% if lang.selected %}active{% endif %}">
                    <a href="/articles/{% update_filters the_filter lang=lang.slug %}">
                        {{ lang.title }}</a>
                </div>
            {% endfor %}
        </div>

        <div class="articles-list">
            {% if article_list %}
                {% for article in article_list %}
                    {% include 'articles/article_item.html' %}
                {% endfor %}
            {% else %}
                No articles found.
            {% endif %}
        </div>

        {% if preview_articles %}
            <div class="preview-articles">
                <h4>Articles in stock</h4>
                {% for article in preview_articles %}
                    <a class="short-link" href="/articles/{{ article.id }}/"> {{ article.title }} </a>
                {% endfor %}
                <h4>
                    <a href="/articles/{% update_filters the_filter page=next_page %}">Watch feed</a> &rarr;
                </h4>
            </div>
        {% endif %}
    </div>

    <div class="articles-rss">
        <div class="articles-rss-img">
            <a href="{% url rss %}">
                <img width="18" height="18" src="/static/techblog/img/common/rss.png" alt="RSS"/>
            </a>
        </div>
        <div class="articles-rss-link">
            <a href="{% url rss %}">Subscribe</a>
        </div>
    </div>

    {% include "articles/control_panel.html" %}

{% endblock content %}

site/source/apps/techblog/templates/articles/comment_form.html
{% load threadedcomments_tags %}

{% get_comment_form for article as form %}

<form class="comment-form" action="/comments/post/" method="post">
    {% csrf_token %}

    {{ form.comment }}

    {% for field in form %}
        {% if field.is_hidden and field.name != 'parent' %}
            {{ field }}
        {% endif %}
    {% endfor %}

    {% if comment %}
        <input type="hidden" name="parent" id="id_parent" value="{{ comment.id }}"/>
        <input type="hidden" name="next" id="id_next" value="/articles/{{ article.id }}/#reply_to_{{ comment.id }}"/>
    {% else %}
        <input type="hidden" name="next" id="id_next" value="/articles/{{ article.id }}/#last_comnent"/>
    {% endif %}

    <p class="submit">
        <input type="submit" name="post" class="submit-post" value="Comment"/>
    </p>
</form>